### ISSUE TITLE
have you considered liftoff?

### ISSUE THREAD

**Issue by tkellen** [sighjs/sigh-cli#3]
[It would...](http://github.com/tkellen/js-liftoff)
- allow configuration files written in any js variant transparently to the cli implementor (that's you)
- cover all the edge cases around finding the local installation of sigh (e.g. relative to config file, or to provided base directory, etc)
- cover all the edge cases around using v8 flags in conjunction with your tool (e.g. automatically respawn a command like `sigh --harmony` to `node --harmony /path/to/sigh`

**Comment by insidewhy** [comment]
Sounds cool, hopefully will get around to adding that someday.

**Comment by insidewhy** [comment]
Hopefully someone who cares enough about the advantages of liftoff will implement support for this in sigh-cli.

I'm going to close this for now as I have too many things in my list of priorities for sigh such that I can't see myself personally implementing this for a long time.
