### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by unlight** [sighjs/sigh-cli#4]
**Node 4.2.1, Windows 8**
`npm install -g sigh-cli` 

npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\X\AppData\Roaming\npm-cach
e_git-remotes_templates --mirror git@github.com:kevva/gulp-decompress.git C:\Users\X\AppData\Roaming\npm-cache_git-remotes\git-github-com-kevva-gulp-decompress-git-ee4cf132bac743f75b4e2cd486b7f4be204e29ba-a4f5
4e1258d4552031c388a65593723f

npm ERR! Permission denied (publickey).
npm ERR! fatal: The remote end hung up unexpectedly

**Comment by insidewhy** [comment]
Can you try `npm cache clean` and then install again. It looks like an issue checking out a dependent repository but it works for me. Don't think it's an issue with `sigh-cli`.

**Comment by unlight** [comment]
Yes. Issue comes from package `download`, it has dependency `github:kevva/gulp-decompress#ee4cf132bac743f75b4e2cd486b7f4be204e29ba`.
I solved issue by downgrading npm to version 2.14.

**Comment by insidewhy** [comment]
I could install it with node 4.2.x
